/**
 * Quarterly estimated taxes → dated cash out.
 *
 * Takes monthly operating profit (from the projections sheet) and a blended
 * rate, and produces the four IRS estimated-tax installments per year. Pure:
 * no I/O, no clock — every date is derived from the profit months themselves.
 *
 * The math is a **year-to-date true-up**, not four independent quarters:
 *
 *     liability(period) = max(0, YTD operating profit through period × rate)
 *     payment(period)   = max(0, liability − everything already scheduled this year)
 *
 * That matters because the business swings between profit and loss month to
 * month. A quarter-in-isolation model would bill tax on a good Q1 and give no
 * credit for a bad Q2; the YTD form lets a later loss shrink (or zero out) the
 * next payment, which is how estimated taxes actually work. The floor at zero
 * reflects that the IRS doesn't hand cash back mid-year — an overpayment just
 * suppresses later installments and settles at filing.
 *
 * "Everything already scheduled" means what was actually APPLIED, not what was
 * theoretically owed. Record a real payment against a quarter and the next
 * quarter trues up against that figure — so underpaying in June raises the
 * September number by the shortfall, and overpaying lowers it. That is the
 * whole point of tracking payments rather than just a paid/unpaid flag.
 */

import type { ISODate } from "../dates.js";
import { daysInMonth } from "../dates.js";
import type { CashEvent, TaxPayment, TaxSettings } from "../types.js";
import { DEFAULT_TAX_RATE } from "../types.js";

/**
 * The four estimated-tax periods for a calendar-year filer. Note they are NOT
 * even quarters — the IRS periods are 3, 2, 3, and 4 months long. Using real
 * calendar quarters would date the June payment a month late.
 */
export interface EstimatedTaxPeriod {
  label: "Q1" | "Q2" | "Q3" | "Q4";
  /** First month covered (1-based). */
  fromMonth: number;
  /** Last month covered, inclusive (1-based). */
  throughMonth: number;
  /** Month the payment is due (1-based). */
  dueMonth: number;
  dueDay: number;
  /** Q4's payment is due in January of the FOLLOWING year. */
  dueYearOffset: 0 | 1;
}

export const ESTIMATED_TAX_PERIODS: readonly EstimatedTaxPeriod[] = [
  { label: "Q1", fromMonth: 1, throughMonth: 3, dueMonth: 4, dueDay: 15, dueYearOffset: 0 },
  { label: "Q2", fromMonth: 4, throughMonth: 5, dueMonth: 6, dueDay: 15, dueYearOffset: 0 },
  { label: "Q3", fromMonth: 6, throughMonth: 8, dueMonth: 9, dueDay: 15, dueYearOffset: 0 },
  { label: "Q4", fromMonth: 9, throughMonth: 12, dueMonth: 1, dueDay: 15, dueYearOffset: 1 },
];

/** One estimated-tax installment, with the full working shown. */
export interface TaxInstallment {
  /** Stable id, e.g. "2026-Q3". Doubles as the CashEvent id. */
  id: string;
  year: number;
  label: EstimatedTaxPeriod["label"];
  /** Inclusive month range this period covers, e.g. "2026-06" … "2026-08". */
  fromMonth: string;
  throughMonth: string;
  /** Last calendar day of `throughMonth` — when this period closes. */
  periodEnd: ISODate;

  /** Operating profit generated by THIS period's months alone. */
  quarterProfit: number;
  /** Cumulative operating profit for the year through `throughMonth`. */
  ytdProfit: number;
  /**
   * Liability this period added — the change in cumulative liability, so a
   * loss-making quarter shows a negative figure (it reduced what you owe).
   */
  quarterLiability: number;
  /** Running total: max(0, ytdProfit × rate) — owed for the year to this point. */
  ytdLiability: number;

  /** Total applied against the year before this installment. */
  appliedBefore: number;
  /** What the rolling true-up says to pay: max(0, ytdLiability − appliedBefore). */
  scheduledAmount: number;
  /** What actually applies — the recorded/overridden amount, else `scheduledAmount`. */
  amount: number;
  /** Running total applied through this installment (`appliedBefore` + `amount`). */
  appliedAfter: number;
  /**
   * Still owed for the year after this installment: `ytdLiability` −
   * `appliedAfter`. Negative means overpaid to date.
   */
  balance: number;

  /** Statutory due date. */
  dueDate: ISODate;
  /** When it is actually paid / planned — the recorded date, else `dueDate`. */
  date: ISODate;
  /** The recorded payment or planned override, when one exists. */
  payment?: TaxPayment;
  /** True when recorded as paid, or covered by the blunt `paidThrough` cutoff. */
  paid: boolean;
  /** True when the amount came from a recorded entry rather than the true-up. */
  overridden: boolean;
  /** Months in the year-to-date window with no profit figure, treated as 0. */
  missingMonths: string[];
}

/**
 * Money is carried to a tenth of a cent. The profit figures arrive from the
 * sheet unrounded (Jan is -21563.570000000065), so rounding the tax to whole
 * dollars threw away real precision and stopped the figures tying back to the
 * source. Three decimal places also clips the float noise that would otherwise
 * surface in the UI.
 *
 * Note this is the *modelled* figure — an actual IRS voucher is paid in whole
 * dollars, so expect a sub-dollar difference against what you really remit.
 */
export const MONEY_DP = 3;

/** Round to a tenth of a cent. */
export function roundMoney(n: number): number {
  return Math.round(n * 1000) / 1000;
}

function monthKey(year: number, month: number): string {
  return `${year}-${String(month).padStart(2, "0")}`;
}

/** Last calendar day of a month, as an ISO date. */
function endOfMonth(year: number, month: number): ISODate {
  const day = daysInMonth(year, month - 1);
  return `${year}-${String(month).padStart(2, "0")}-${String(day).padStart(2, "0")}`;
}

function dueDateFor(year: number, period: EstimatedTaxPeriod): ISODate {
  const y = year + period.dueYearOffset;
  return `${y}-${String(period.dueMonth).padStart(2, "0")}-${String(period.dueDay).padStart(2, "0")}`;
}

/** The distinct calendar years present in a monthly-profit map, ascending. */
export function profitYears(monthlyProfit: Record<string, number>): number[] {
  const years = new Set<number>();
  for (const key of Object.keys(monthlyProfit)) {
    const year = Number(key.slice(0, 4));
    if (Number.isFinite(monthlyProfit[key]) && Number.isInteger(year)) years.add(year);
  }
  return [...years].sort((a, b) => a - b);
}

/**
 * Build the full installment schedule — every period of every year that has at
 * least one month of profit data. Returns the schedule whether or not each
 * installment is payable, so the UI can show zeros and already-paid periods
 * (a $0 payment because losses wiped out the liability is information, not
 * nothing). Use `taxEvents` for the subset that actually moves cash.
 */
export function taxInstallments(settings: TaxSettings): TaxInstallment[] {
  const monthlyProfit = settings.monthlyProfit ?? {};
  const payments = settings.payments ?? {};
  const rate = Number.isFinite(settings.rate) ? settings.rate : DEFAULT_TAX_RATE;
  const out: TaxInstallment[] = [];

  for (const year of profitYears(monthlyProfit)) {
    // What has actually been APPLIED so far this year — recorded payments where
    // they exist, computed amounts otherwise. Truing up against this (rather
    // than against what was theoretically owed) is what makes a shortfall in
    // one quarter roll into the next.
    let applied = 0;
    let prevYtdLiability = 0;

    for (const period of ESTIMATED_TAX_PERIODS) {
      // YTD runs from January, not from the period start — that's what makes a
      // later loss claw back an earlier quarter's liability.
      let ytdProfit = 0;
      let quarterProfit = 0;
      const missingMonths: string[] = [];
      for (let m = 1; m <= period.throughMonth; m++) {
        const key = monthKey(year, m);
        const value = monthlyProfit[key];
        if (typeof value === "number" && Number.isFinite(value)) {
          ytdProfit = roundMoney(ytdProfit + value);
          if (m >= period.fromMonth) quarterProfit = roundMoney(quarterProfit + value);
        } else {
          missingMonths.push(key);
        }
      }

      const ytdLiability = Math.max(0, roundMoney(ytdProfit * rate));
      // The change in what you owe. Negative when the quarter lost money — the
      // period genuinely reduced the year's liability.
      const quarterLiability = roundMoney(ytdLiability - prevYtdLiability);
      const scheduledAmount = Math.max(0, roundMoney(ytdLiability - applied));

      const id = `${year}-${period.label}`;
      const payment = payments[id];
      const overridden = payment !== undefined && Number.isFinite(payment.amount);
      const amount = overridden ? Math.max(0, roundMoney(payment!.amount)) : scheduledAmount;

      const dueDate = dueDateFor(year, period);
      const appliedBefore = applied;
      applied = roundMoney(applied + amount);

      out.push({
        id,
        year,
        label: period.label,
        fromMonth: monthKey(year, period.fromMonth),
        throughMonth: monthKey(year, period.throughMonth),
        periodEnd: endOfMonth(year, period.throughMonth),
        quarterProfit,
        ytdProfit,
        quarterLiability,
        ytdLiability,
        appliedBefore,
        scheduledAmount,
        amount,
        appliedAfter: applied,
        balance: roundMoney(ytdLiability - applied),
        dueDate,
        date: payment?.date ?? dueDate,
        ...(payment ? { payment } : {}),
        paid:
          payment?.paid === true ||
          (payment?.paid === undefined &&
            settings.paidThrough !== undefined &&
            dueDate <= settings.paidThrough),
        overridden,
        missingMonths,
      });

      prevYtdLiability = ytdLiability;
    }
  }

  return out;
}

/** Year-level totals for the summary strip. */
export interface TaxYearSummary {
  year: number;
  /** Last complete calendar month counted, "YYYY-MM". */
  accruedThroughMonth: string | null;
  /**
   * Liability accrued through the last COMPLETE MONTH — not the last closed
   * quarter. Quarter-based accrual is up to three months stale, which reads as
   * broken when it exceeds the full-year figure.
   */
  liabilityAccrued: number;
  /** Full-year liability on current projections. */
  liabilityFullYear: number;
  /** Sum of installments recorded as paid. */
  paidToDate: number;
  /** Sum of unpaid installments still to leave the bank. */
  scheduledAhead: number;
  /**
   * How far paying the schedule as it stands would overshoot the year's
   * liability: (paid + scheduled) − full year, floored at zero.
   *
   * This is the number that matters when payments have been skipped early in a
   * loss-making year. The catch-up installment is computed on profit to that
   * point, but if the rest of the year loses money the excess is not owed —
   * it just sits with the IRS until filing.
   */
  overpaymentIfPaidAsScheduled: number;
  /** The next installment that will actually move cash, if any. */
  next: { id: string; label: string; date: ISODate; amount: number } | null;
}

/**
 * Roll the schedule up per year, as of a given date.
 *
 * `asOf` is passed in rather than read from a clock so this stays pure and
 * testable, like the rest of the engine.
 */
export function taxYearSummaries(settings: TaxSettings, asOf: ISODate): TaxYearSummary[] {
  const installments = taxInstallments(settings);
  const monthlyProfit = settings.monthlyProfit ?? {};
  const rate = Number.isFinite(settings.rate) ? settings.rate : DEFAULT_TAX_RATE;
  const years = [...new Set(installments.map((i) => i.year))].sort((a, b) => a - b);

  return years.map((year) => {
    const rows = installments.filter((i) => i.year === year);
    const last = rows[rows.length - 1]!;

    // Accrue month by month, stopping at the last month that has fully elapsed.
    let accrued = 0;
    let accruedThroughMonth: string | null = null;
    for (let m = 1; m <= 12; m++) {
      if (endOfMonth(year, m) > asOf) break;
      const v = monthlyProfit[monthKey(year, m)];
      if (typeof v === "number" && Number.isFinite(v)) accrued = roundMoney(accrued + v);
      accruedThroughMonth = monthKey(year, m);
    }

    const paidToDate = roundMoney(rows.filter((i) => i.paid).reduce((s, i) => s + i.amount, 0));
    const unpaid = rows.filter((i) => !i.paid && i.amount > 0);
    const scheduledAhead = roundMoney(unpaid.reduce((s, i) => s + i.amount, 0));
    const next = unpaid.find((i) => i.date >= asOf) ?? null;

    return {
      year,
      accruedThroughMonth,
      liabilityAccrued: Math.max(0, roundMoney(accrued * rate)),
      liabilityFullYear: last.ytdLiability,
      paidToDate,
      scheduledAhead,
      overpaymentIfPaidAsScheduled: Math.max(
        0,
        roundMoney(paidToDate + scheduledAhead - last.ytdLiability),
      ),
      next: next ? { id: next.id, label: next.label, date: next.date, amount: next.amount } : null,
    };
  });
}

/**
 * The installments that actually move cash: skips $0 payments and anything
 * already paid. Emitted as `committed` basis — an estimated tax payment is
 * real cash leaving on a known date, even though the profit behind it is a
 * projection, so it belongs in the default forecast rather than behind the
 * `includeBudgeted` toggle.
 */
export function taxEvents(settings: TaxSettings | undefined): CashEvent[] {
  if (!settings?.enabled) return [];
  const ratePct = `${((settings.rate ?? DEFAULT_TAX_RATE) * 100).toFixed(1).replace(/\.0$/, "")}%`;
  return taxInstallments(settings)
    .filter((i) => !i.paid && i.amount > 0)
    .map((i) => ({
      id: `tax:${i.id}`,
      category: "taxes" as const,
      amount: i.amount,
      date: i.date,
      basis: "committed" as const,
      memo: i.overridden
        ? `Estimated taxes ${i.label} ${i.year} — planned amount` +
          (i.payment?.note ? ` (${i.payment.note})` : "")
        : `Estimated taxes ${i.label} ${i.year} — ${ratePct} of YTD operating profit`,
    }));
}
